### ISSUE TITLE
Move in some numerical tools

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#112]
I have a growing collection of numerical tools, many of which can be found in spencerlyon2/CompEcon.jl

What is the team's position on including them here? Should we move the polished/tested ones into QuantEcon.jl?

Motivation for this is partly spencerlyon2/CompEcon.jl#26

cc @davidanthoff

**Comment by jstac** [comment]
@spencerlyon2 I think yes.  @cc7768 Perhaps we could walk through some of this on Monday when we meet.
