### ISSUE TITLE
Forcing 2d arrays in robustlq.jl

### ISSUE THREAD

**Issue by albep** [QuantEcon/QuantEcon.jl#134]
@spencerlyon2 Testing the plots in this [PR](https://github.com/QuantEcon/QuantEcon.applications/pull/63) I couldn't run `robustness/robust_monopolist.jl` because of the following issue:

in `lqcontrol.jl` I added an internal function `getZ` to obtain a conformable element (matrix or number) `Z` to be passed to the function `cond()`. In order for `robust_monopolist.jl` to work following this change, we should then make `C` a `Vector` in this line https://github.com/QuantEcon/QuantEcon.applications/blob/master/robustness/robust_monopolist.jl#L61 (it is now a 2d array). However, when passing a 1d array, [RBLQ here](https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/robustlq.jl#L57) forces a 2d array. Therefore I don't see a way to make `robust_monopolist.jl` work unless we i) change `getZ` again ii) change `RBLQ`.

What would you suggest we do?

**Comment by spencerlyon2** [comment]
Hey @albep I would vote for adding one more method to `getZ`. The main reason is that I would like the "hard work" with the type system to be done inside the library so users don't have to think about it. 

I believe the target audience for _users_ of QuantEcon.jl is similar to the audience for the lectures website. That being the case, we don't want to make them think about the type system when we could handle it ourselves .

@jstac any comments here?

**Comment by jstac** [comment]
That sounds sensible to me.

**Comment by albep** [comment]
@spencerlyon2 I definitely agree with you. Before I implement it, let's check how `getZ` would then look like. It now has 3 [methods](https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/matrix_eqn.jl#L173):

""
- `BB::Float64` : result of B' * B
- `gamma::Float64` : parameter in the Riccati equation solver
- `R::Float64`
##### Returns
- `::Float64` : element Z in the Riccati equation solver
""

""
- `BB::Array{Float64, 1}` : result of B' * B
- `gamma::Float64` : parameter in the Riccati equation solver
- `R::Float64`
##### Returns
- `::Float64` : element Z in the Riccati equation solver
""

""
- `BB::Matrix` : result of B' * B
- `gamma::Float64` : parameter in the Riccati equation solver
- `R::Matrix`
##### Returns
- `::Matrix` : element Z in the Riccati equation solver
""

I guess what you're saying is we should add another method which goes: if you're passing me `R::Float64` and  `BB::Array{Float64, 2}`, I do the same thing as if you passed me a  `BB::Array{Float64, 1}`, i.e. `R + gamma * BB[1]`

**Comment by spencerlyon2** [comment]
Hmm that's a bit tricky. Do we know that this `Matrix` will only have one element?

**Comment by albep** [comment]
If `R` is a `Float`, `BB[1]` must have only 1 element

**Comment by spencerlyon2** [comment]
Ok sounds good. I think that sounds good then. We can probably do this by just relaxing the function signature on the second method to be

```julia
getZ(R::Float64, gamma::Float64, BB::Union{Vector,Matrix})
```

instead of 

```julia
getZ(R::Float64, gamma::Float64, BB::Array{Float64, 1})
```

**Comment by albep** [comment]
Thanks @spencerlyon2, I implemented this in PR #135

**Comment by spencerlyon2** [comment]
Excellent, if this is now resolved will you please close the issue?

**Comment by albep** [comment]
Sure, thanks!
