### ISSUE TITLE
Julia 0.6 dependency warnings

### ISSUE THREAD

**Issue by colbec** [QuantEcon/QuantEcon.jl#140]
Running Pkg.test in Julia v 0.6 produces a number of warnings related to change of functions abs(), cos(), exp() and sqrt() to a dotted version such as abs.(). I started a pull request to offer these changes but suddenly realized this may have backward effects for other versions where the dotted version is not known. So I will hold off on this, but the work remains in https://github.com/colbec/QuantEcon.jl/tree/colbec-patch-2 which may be of use. Advice would be appreciated.

**Comment by spencerlyon2** [comment]
Thank you for doing that. I'm sure that once 0.5 is released and efforts are shifted to 0.6, there will be an official way to do this -- perhaps via Compat.jl. 

cc @stevengj

**Comment by stevengj** [comment]
See the discussion at JuliaLang/Compat.jl#280, cc @yuyichao
