### ISSUE TITLE
HEADS UP: Breaking change in LightGraphs API

### ISSUE THREAD

**Issue by sbromberger** [QuantEcon/QuantEcon.jl#141]
Sorry if this is not relevant to your use of LightGraphs, but I wanted to make sure you’re aware of a change in the API for the `induced_subgraph()` function.

Starting in LightGraphs 0.7.1, `induced_subgraph()` will, in addition to the subgraph itself, return a mapping of the original vertex indices to the new ones. This will require code changes to ignore the new return value if you’re using this function.

If you’re using the `getindex` version of `induced_subgraph` (that is, `g[1:5]`), there will be no change.

Feel free to close this out if it’s not applicable to your use of LightGraphs. Thanks!

**Comment by spencerlyon2** [comment]
Thank you for letting us know. I'll check out our usage and make any changes that are needed

**Comment by spencerlyon2** [comment]
@sbromberger I think that all of our LightGraphs usage is restricted to [these functions](https://github.com/QuantEcon/QuantEcon.jl/blob/7f9ddf2f3c638b365650d9b3fe68a34c80522f36/src/markov/mc_tools.jl#L13-L14), I think we are probably safe from this breaking change then, right?

**Comment by sbromberger** [comment]
Yes. You should be fine. If any of those functions rely on induced sub graphs, we will fix (have already fixed) them to use the new results. 

Cheers!
