### ISSUE TITLE
Loss of significance in Rouwenhorst AR(1) approximation?

### ISSUE THREAD

**Issue by MaximilianJHuber** [QuantEcon/QuantEcon.jl#145]
Hi,

Jarda Borovicka gave a problem set containing [Finite state Markov-chain approximations to highly persistent processes](http://www.sciencedirect.com/science/article/pii/S1094202510000128). The authors proof an alternative (polynomial) construction of Rouwenhorst's method in Appendix A. 

I implemented this method and found a performance increase,
`@time rouwenhorst(21,0.99,(1-0.95^2)^(1/2));`
0.000286 seconds (1.25 k allocations: 405.000 KB)

`@time alternative_rouwenhorst(21,0.99,(1-0.95^2)^(1/2));`
0.000042 seconds (12 allocations: 4.063 KB)

but more importantly significant numerical differences. I guess there is a lot of cancellation going on in the recursive implementation in the QuantEcon package. I would suggest a switch to the polynomial construction below, but there is one issue remaining:

I find that with higher grid sizes, the rows of the transition matrix do not add up to one (and thus I cannot create a QuantEcon-MarkovChain object):

`(p,s) = alternative_rouwenhorst(21,0.99,(1/0.95^2)^(1/2))`
`[sum(p[i,:]) for i in 1:21]`
Any[0.9999999999999999,1.0,0.9999999999999999,1.0,0.9999999999999999,1.0,1.0,1.0,1.0,1.0,1.0000000000000002,1.0000000000000002,0.9999999999999999,0.9999999999999565,0.999999999994664,0.999999999470605,0.9999999579541284,0.9999973881686884,0.9998775997510598,0.9959209147866287,1.0]

I would highly appreciate a second pair of eyes on my code!

```
function alternative_rouwenhorst(N::Integer, ρ::Real, σ::Real, μ::Real=0.0)
    p = (1+ρ)/2
    q = p
    Ψ = (N-1)^(1/2)*σ/((1-ρ^2)^(1/2))
    m = μ/(1-ρ)
    
    states = collect(linspace(m-Ψ,m+Ψ,N))
    P = zeros(Float64,N,N)
    
    #for all calculations see http://dx.doi.org/10.1016/j.red.2010.02.002 page 711
    
    for j in 1:N #top and bottom row
        P[1,j] = binomial(N-1,j-1)*p^(N-j)*(1-p)^(j-1)
        P[N,j] = binomial(N-1,j-1)*(1-q)^(N-j)*q^(j-1)
    end
    
    for i in 2:(N-1) #rows in the middle
        P[i,1] = (1-q)^(i-1)*p^(N-1) #first column
        for j in 2:N #other columns
            P[i,j] = (1-q)*P[i-1,j] + q*P[i-1,j-1]
        end
    end
    
    return (P, states)
end

**Comment by oyamad** [comment]
I just had a quick look at page 711 in that paper, but wondered how one can ever get the last two terms in (15) with superscripts N. I suspect they are typos for N-1. Note that the main formulas (12)-(13) are recursive formulas in N.

**Comment by MaximilianJHuber** [comment]
You were spot on! Now the results are numerically identical, but the performance gain is gone of course. I will try to get the runtime down, but otherwise the issue is closed.

**Comment by spencerlyon2** [comment]
Thanks @MaximilianJHuber and @oyamad. 

I'm happy to see that the routines agree and that the performance of the one in Quantecon is competitive.
