### ISSUE TITLE
qnwnorm not type stable

### ISSUE THREAD

**Issue by albop** [QuantEcon/QuantEcon.jl#148]
When I compare the output of the two following lines:
 ```
x,w = QE.qnwnorm([3], [0.0], eye(3))
x,w = QE.qnwnorm([3 3], [0.0, 0.0], eye(2))
```
I find that `x` is a vector in the first case and a one line matrix in the second case. I would suggest to adopt a consistent behaviour (the second), or alternatively to have another function `qnwmvnorm` or smthg like that.
I think the behaviour changed in the last release of QuantEcon.

**Comment by spencerlyon2** [comment]
I have a fix locally -- I take type-instability personally ;)

Will patch up and submit a PR sometime today

**Comment by spencerlyon2** [comment]
Done

**Comment by albop** [comment]
Cool, I feel much more stable now...
