### ISSUE TITLE
Question: change `draw(::DiscreteRV)` to `rand(::DiscreteRV)`?

### ISSUE THREAD

**Issue by sglyon** [QuantEcon/QuantEcon.jl#162]
What do people think about changing the function name for getting a random sample from a DiscreteRV from `draw` to `rand`? The `rand` function seems to be the right name in the Julia ecosystem.

I'd also be open to having these two names be synonyms for one another.

cc @jstac

**Comment by jstac** [comment]
I think it's fine to change to `rand` --- and a good idea for the reasons you suggest.  There's no need to keep `draw`.  

We're close to having automatic daily testing on all our lecture code now, so even if I forget to make the change the error will be picked up when the new version of the library goes live ;-)

**Comment by sglyon** [comment]
Automatic testing sounds great! 

Ok, I'll make the change. For now I'll leave `draw` in as a deprecated function

**Comment by sglyon** [comment]
Change is now active in METADATA.jl registered version of QuantEcon
