### ISSUE TITLE
Drop ecdf?

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.jl#186]
Currently `ecdf` is available in StatsBase, leading to the warning

> both StatsBase and QuantEcon export "ecdf"; uses of it in module Main must be qualified

The StatsBase version is here:

https://github.com/JuliaStats/StatsBase.jl/blob/7e9d724cd795a719f340d6102c8b714ccec3cbde/src/empirical.jl#L5-L13

**Comment by sglyon** [comment]
I'm in favor

**Comment by a-parida12** [comment]
I am interested in resolving this bug. Can someone guide me on how to approach it?

**Comment by sglyon** [comment]
Hi @a-parida12 thanks for being willing to work on it.

I think it should be as simple as making our name `ECDF` go directly to the `StatsBase.ecdf` 

The one thing we lose is the ability to look up the `observations` field on what gets returned by `StatsBase.ecdf`.

Does anyone see that as an issue? @jstac ?

**Comment by jstac** [comment]
That's fine at this end.
