### ISSUE TITLE
Support for 1.0

### ISSUE THREAD

**Issue by Nosferican** [QuantEcon/QuantEcon.jl#210]
Opening an issue to keep track of the progress towards supporting 0.7.

**Comment by femtotrader** [comment]
This is probably something that might be considered for JuliaCon2018 Hackathon
https://discourse.julialang.org/t/recruiting-package-authors-for-juliacon-hackathon-mentoring-guidance/12453

**Comment by Nosferican** [comment]
We can probably run FemToCleaner and make a dev branch to get us pretty close. At least to the point that allows us to develop [Expectations.jl](https://github.com/econtoolkit/Expectations.jl) and update [QuantEcon Lectures (Julia)](https://lectures.quantecon.org/jl/).

**Comment by sglyon** [comment]
That sounds great.

**Comment by Nosferican** [comment]
A few issues I identified
- [ ] Doctrings (find a way to display them with \LaTeX or use only unicode)
- [ ] Iterator syntax
- [ ] Use of `Nullable`
- [ ] Certain code seems to have broken for LinearAlgebra routines

**Comment by Nosferican** [comment]
List of files to update in `src` (update the file and the related test file)
- If the functionality is available in another package already, use outside package (check if supports 1.0)
- Legacy code should be replaced or ported à la Julian

- [ ] arma.jl
- [ ] compute_fp.jl
- [ ] discrete_rv.jl
- [ ] ecdf.jl
- [ ] estspec.jl
- [ ] filter.jl
- [ ] interp.jl
- [ ] kalman.jl
- [ ] lae.jl
- [ ] lqcontrol.jl
- [ ] lqnash.jl
- [ ] lss.jl
- [ ] matrix_eqn.jl
- [ ] optimization.jl
- [ ] quad.jl
- [ ] quadsums.jl
- [ ] robustlq.jl
- [ ] sampler.jl
- [ ] util.jl
- [ ] zeros.jl

**Comment by Nosferican** [comment]
Finding replacements and porting code out of QuantEcon to reduce size.
- [ ] `fix` and `fix!` should use `trunc`
- [ ] `gridmake` (should probably use a Julian way, e.g., broadcast rather than the `Matrix`, but for now changed from the 50+ lines to
```
gridmake(arrays::AbstractVecOrMat...) =
    reduce(vcat, transpose(collect(flatten(elem)))
    for elem ∈ product((array isa AbstractVector ?
        array :
        [ array[row:row,:] for row ∈ 1:size(array, 1) ]
    for array ∈ arrays)...))
```
- [ ] Function/files that could be moved to [Combinatorics.jl](https://github.com/JuliaMath/Combinatorics.jl)
  - [ ] `num_compositions` (seems to be used as a helper)
  - [ ] `simplex_grid`, `simplex_index`, `next_k_array!`, `k_array_rank`
- [ ] Functions/files that could be ported or replaced by [Roots.jl](https://github.com/JuliaMath/Roots.jl)
  - [ ] `src/zeros.jl`
- [ ] Functions/files that could be ported or replaced by [Expectations.jl](https://github.com/econtoolkit/Expectations.jl)
  - [ ] `src/interp.jl`
- [ ] Functions/files that could be ported or replaced by [StatsBase.jl](https://github.com/JuliaStats/StatsBase.jl)
  - [ ] `src/discrete_rv.jl`

**Comment by Nosferican** [comment]
I believe the plan is to tag a 1.0 version compatible for now and later on engage in a major re-write with some breaking changes (using deprecation warnings to allow people to update code). Julia 0.7 is not a true release and is meant to be used for code updating only. Having a 1.0 release will allow others to update their code using 0.7 and we are keeping the same API for now. Development and the re-write process should probably focus on 1.x.y versions then.

**Comment by sglyon** [comment]
@oyamad I don't plan to have a new release that supports both 0.6 and 0.7+. Though, if you can argue a reason why we should, I'm happy to hear it and consider

As for how we will get to the 0.7+-ready release I've been biding my time until our dependencies are all ready to go. Once that happens there are a few things that need to be changed (@Nosferican has been working on them already), but it shouldn't be too monumental of an effort. 

- - -

As for the 

>  major re-write with some breaking changes

I can't say too much. I haven't really been involved with these discussions. My suspicion is that we will be able to leverage new Julia features to simplify some things, but that most of the code will remain intact and continue to work.

**Comment by Shunsuke-Hori** [comment]
I kind of want a new 0.6 compatible release before #215 because new features between #215 and [the last release (v0.14.2)](https://github.com/QuantEcon/QuantEcon.jl/releases/tag/v0.14.2) are not officially available in 0.6 now.

**Comment by Shunsuke-Hori** [comment]
@Nosferican 

> Would that be just a release of current master? 

Yes, exactly.

**Comment by sglyon** [comment]
In the works right now: https://github.com/JuliaLang/METADATA.jl/pull/17219

**Comment by Nosferican** [comment]
Closed by https://github.com/JuliaLang/METADATA.jl/pull/17534
