### ISSUE TITLE
Lecture Note Upgrades

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/QuantEcon.jl#212]
Talked with @nosferican about opening this to track the integrations of the outside code into the lectures. In particular, what we have right now in terms of external code is: 

- [ ] Econtoolkit/Expectations.jl: Works on 0.7 and 0.6, through Compat. Depends itself on FastGaussQuadrature.jl, which AFAIK has gotten rid of its deprecation warnings. 
- [ ] mauro3/Parameters.jl: Latest tagged release (`0.9.1`) supports the `@with_kw` named tuple generators on v0.7. i.e., 

```
params = @with_kw (x = 0.5, y = 2, f = x -> x^2)
params() # Returns the named tuple with defaults. 
params(x = 3) # Returns (x = 3, y = 2, f = x -> x^2)
@unpack x, y, f = ... # Will carry out those assignments. 
```

- [ ] JuliaNLsolvers/NLsolve.jl: There is a PR open to incorporate basic fixed-point support (univariate functions, in place or out of place, with gradients computed by autodifferentiation **only**). Once it's merged, that is good to go.

José can let me know if I missed anything.

**Comment by pkofod** [comment]
> JuliaNLsolvers/NLsolve.jl: There is a PR open to incorporate basic fixed-point support (univariate functions, in place or out of place, with gradients computed by autodifferentiation only). Once it's merged, that is good to go.

this should be merged

**Comment by arnavs** [comment]
Expectations is also tagged through 1.0

**Comment by Nosferican** [comment]
Might be nice to follow the new Iterpolations.jl which should be done soon. From what Chris explained, it seemed like a great improvement (going from trapezoid libraries to a function integral approach for greater precision and more efficient).

**Comment by pkofod** [comment]
> done soon
Is this "soon" or soon?

**Comment by arnavs** [comment]
Sure, I'll keep an eye on it. It looks like [this](https://github.com/JuliaMath/Interpolations.jl/issues/224) is the issue to track.
