### ISSUE TITLE
Documenter not working

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.jl#239]
See https://travis-ci.org/QuantEcon/QuantEcon.jl/jobs/501549954#L986

Cf. QuantEcon/Games.jl#99

**Comment by sglyon** [comment]
Thanks for pointing this out. Do you have any RAs with time to help us get this sorted out?

**Comment by oyamad** [comment]
@shizejin Would you have time to work on this, as you did for `Games`?

**Comment by shizejin** [comment]
Sure! I will look into this.
