### ISSUE TITLE
QuantEcon Julia: a list of the routines used

### ISSUE THREAD

**Issue by Echetlaeus** [QuantEcon/QuantEcon.jl#24]
Hello,

I am trying to learn Julia through the lecture notes by Prof. Sargent and Stachurski. In the manuscript , when `QuantEcon` is utilized they use specific packages (routines) like `tauchen`.

Where one can find the full list of the routines used  plus, maybe, a short description of them?

**Comment by spencerlyon2** [comment]
Documentation is (for now) [here](http://quantecon.github.io/QuantEcon.jl/)

We might relocate to readthedocs, but will update a link the README if that happens.

The list of routines supplied by the package can be found on the [overview page](http://quantecon.github.io/QuantEcon.jl/api/) of the docs.
