### ISSUE TITLE
URL in repository's description is broken

### ISSUE THREAD

**Issue by mvinoba** [QuantEcon/QuantEcon.jl#254]
Repository's description has this URL: [http://quantecon.org/julia_index.html](http://quantecon.org/julia_index.html). This is a **"Page Not Found"** error in QuantEcon.

**Comment by zdroid** [comment]
> Currently, repository's URL (next to description) points to http://quantecon.org/julia_index.html. It should be https://quantecon.org/quantecon-jl/ instead.

That's the fix for this.

**Comment by oyamad** [comment]
@mvinoba @zdroid Thanks! Fixed.
