### ISSUE TITLE
Quantitative Economics with Julia - Documentation PDF 

### ISSUE THREAD

**Issue by Sinansi** [QuantEcon/QuantEcon.jl#257]
Hello,

What happened to the PDF documentation version of this library?
About 800 pages are removed from the book?
It was 1048 pages last year, now it is only 194 pages.

The pdf download link:
https://julia.quantecon.org/

Thank you!

**Comment by jstac** [comment]
Thanks @Sinansi, your report is much appreciated.  We'll look into it immediately.

BTW, [this repo](https://github.com/QuantEcon/lecture-source-jl) is specific to the lectures.

**Comment by Sinansi** [comment]
The original book had the following sections:
Part 1: Getting Started with Julia
Part 2: Packages and Software Engineering in Julia
Part 3: Tools and Techniques
Part 4: Dynamic Programming
Part 5: Multiple Agent Models
Part 6: Time Series Models
Part 7: Dynamic Programming Squared

Now the downloadable version has Parts 1 & 2 only.

**Comment by mmcky** [comment]
thanks @Sinansi -- we are working on a fix for the incomplete `pdf` generation.
