### ISSUE TITLE
Julia issue : ERROR: UndefVarError: JacobiRec not defined

### ISSUE THREAD

**Issue by SuyongYang** [QuantEcon/QuantEcon.jl#265]
Hello, I'm practicing the Julia codes in "Quantitative Economics with Julia (2020)" with my Ubuntu computer. 
It's so far satisfactory, but I got
some problems with implementing the codes regarding 'On the Jog Search' on Chapter 30.

I typed the codes exactly, but repeatedly got the error message mentioned above.

I tried updating the regarding packages, but still swamped in the problematic message without any

progress. Can anybody help?

**Comment by SuyongYang** [comment]
I finally fixed it which was dependency problem.

**Comment by sglyon** [comment]
Excellent, thank you!
