### ISSUE TITLE
PY: cartesian

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#31]
We don't have a direct representation of the `cartesian` module from the python side.

I think the function in the python library is actually somewhat like the `repeat` function from the Julia standard library. @albop, can you confirm that?

**Comment by albop** [comment]
Yes, kind of.  Each column of the cartesian grid can be constructed using repeat. For instance, `[1,1,1,2,2,2,3,3,3,1,1,1,2,2,2,3,3,3]` can be constructed with with `repeat([[1,2,3]], inner=[3,1], outer=[2,1])`. The helper function I ended up writing was there to compensate for the lack of such a function.
It should be very easy to replicate the cartesian function in julia using `repeat` (in that case it would be nice to keep the option to choose C or F ordering). Now I guess there are other functions out there to do that (like Timholy's Cartesian.jl ) or a clever syntax to do a one liner (here I'm just speculating).

**Comment by spencerlyon2** [comment]
I don't think we need `cartesian`. The new `CartesianIndex` and `CartesianRange` types in 0.4 will be a simpler/more performant way to do this.
