### ISSUE TITLE
PY: gth_solve

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#33]
Don't have a julia version of the gth_solve module

**Comment by oyamad** [comment]
gth_solve is contained in [mc_tools.jl](https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/mc_tools.jl#L72).

See also:
[Add gth support to mc_compute_stationary](https://github.com/QuantEcon/QuantEcon.jl/pull/26).

**Comment by spencerlyon2** [comment]
Ahh yes, that's right. Thanks for the reminder.
