### ISSUE TITLE
PY: ivp

### ISSUE THREAD

**Issue by sglyon** [QuantEcon/QuantEcon.jl#34]
We don't have a Julia version of the ivp module

**Comment by spencerlyon2** [comment]
Moving this to v0.3 milestone

**Comment by rawls238** [comment]
going to be working on this over the next couple weeks unless someone else has already done this and hasn't marked this issue as closed

**Comment by spencerlyon2** [comment]
@rawls238 that would be great.

No one is currently assigned and the work has not been done yet.

**Comment by rawls238** [comment]
@spencerlyon2 awesome! I'll start working on this then

**Comment by rawls238** [comment]
Started doing this but got distracted by other stuff...hopefully will have this done sometime in the next couple weeks

**Comment by spencerlyon2** [comment]
No problem.

Thanks for the update.
