### ISSUE TITLE
PY: matrix_eqn

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#35]
Don't have a julia version of the matrix_eqn module

**Comment by ZacCranko** [comment]
I'm tackling this one

**Comment by ZacCranko** [comment]
@spencerlyon2 it looks like we already have a matrix_eqn.jl?

**Comment by spencerlyon2** [comment]
Yeah it looks like we do. Before closing this will you make sure we provide at least all the functionality from the python module?

**Comment by ZacCranko** [comment]
Yep, all the functionality is already there along with tests.

**Comment by spencerlyon2** [comment]
Nice. Feel free to close this issue!

// Spencer

On June 17, 2015 at 9:51:46 PM EDT, Zac Cranko <notifications@github.com> wrote:Yep, all the functionality is already there along with tests.   —Reply to this email directly or view it on GitHub.

**Comment by ZacCranko** [comment]
Would love to, but I don't have permission.

**Comment by spencerlyon2** [comment]
Closing now. Thanks.
