### ISSUE TITLE
PY: robustlq

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#37]
We don't have a Julia version of the robustlq module

**Comment by cc7768** [comment]
It looks like this was mostly done before, but I've gone through and cleaned it up a little. I also added the Python docs, but will convert to a more Julia-esque format soon.

**Comment by spencerlyon2** [comment]
Thanks for looking at it and making sure it was running fine.

I'll take a look and try to get this issue closed. Will , probably look tomorrow.

**Comment by spencerlyon2** [comment]
I think this was closed by #50 

Thanks @cc7768
