### ISSUE TITLE
typo in ifp.jl code

### ISSUE THREAD

**Issue by isutoris** [QuantEcon/QuantEcon.jl#38]
I've been browsing through QuantEcon code for income fluctuations problem, and noticed probable typo in definition of get_greedy! operator at src/models/ifp.jl, line 96:

```
function get_greedy!(cp::ConsumerProblem, V::Matrix, out::Matrix)
    bellman_operator!(cp, v, out, ret_policy=true)
end
```

The input array with value function values is denoted V, but bellman_operator! is then called with lowercase v (although it looks like that the inplace version of get_greedy is not called in examples or tests, so this hasn't caused problems).

**Comment by jstac** [comment]
@isutoris Many thanks for picking this up and letting us know.  Much appreciated.  @spencerlyon2 I'll leave you to make the change assuming you agree.

**Comment by spencerlyon2** [comment]
Oh yes, definitely a typo here. I'll make the fix and close the issue. 

Thanks @isutoris
