### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#47]
Now that the doctoring mechanism in 0.4 is stable, we should start adding them to all of our routines. 

Most of the text can be borrowed from the python docstrings, but we would want to do heavy reformatting to match the conventions established in the docs for methods in `Base`

This should address #24

**Comment by cc7768** [comment]
Would be nice to have a wiki on what the docs in Julia should look like or maybe a link to point us in the right direction.

**Comment by spencerlyon2** [comment]
Great point, are you volunteering :wink: ?

**Comment by spencerlyon2** [comment]
closed by #50
