### ISSUE TITLE
BUG: mc_tools non-determinism

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#49]
Found this while combing through deprecation warnings:

```
julia> using QuantEcon

julia> P1 = [1 0 0; .2 .5 .3; 0 0 1];

julia> d1 = MarkovChain(P1);

julia> QuantEcon.irreducible_subsets(d1)
3-element Array{Array{Int64,1},1}:
 [1]
 [2]
 [3]

julia> QuantEcon.irreducible_subsets(d1)
1-element Array{Array{Int64,1},1}:
 [1,2]

julia> QuantEcon.irreducible_subsets(d1)
1-element Array{Array{Int64,1},1}:
 [1]

julia> QuantEcon.irreducible_subsets(d1)
1-element Array{Array{Int64,1},1}:
 [2]

julia> QuantEcon.irreducible_subsets(d1)
2-element Array{Array{Int64,1},1}:
 [2]
 [3]
```

Shouldn't the `irreducible_subsets` of a given stochastic matrix be constant?

@ZacCranko any ideas what's going on here?

**Comment by ZacCranko** [comment]
I have 0 idea what's going on here, but I'll be relocating/reprogramming this stuff into LightGraphs when #32 is addressed.

**Comment by oyamad** [comment]
On [L155](https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/mc_tools.jl#L155) in `irreducible_subsets`:

```
p = similar(mc.p, Bool)
```

if I understand correctly, `similar` corresponds to `numpy.empty_like`, so `p` is left uninitialized without being populated. I guess this is why the result is undetermined.

Maybe we need something like:

```
p[:] = mc.p
```

One problem is that we forgot to port tests for communication classes and so on from the Python side (but why do we have different terminologies between the Python and Julia versions?).

**Comment by jstac** [comment]
1 vote for conforming to @oyamad 's terminology on the Python side.  That code is carefully constructed and very well documented.

**Comment by spencerlyon2** [comment]
Another vote from me!

**Comment by ZacCranko** [comment]
In keeping with trying not to locate graph algorithms in Quant Econ my plan was to have the core of this code in an algorithm called something like `sink_strongly_connected` in LightGraphs.jl, but I agree regarding the terminology.

**Comment by spencerlyon2** [comment]
I think it would be great to have the generic graph theory components in LightGraphs instead of QuantEcon-- partially because I don't know enough about them to sign off on maintaining them going forward :smirk:

**Comment by ZacCranko** [comment]
You're not missing out on much Spencer, graph algorithms might just be the worst thing ever.

**Comment by spencerlyon2** [comment]
@oyamad good eye on that one.

Changing that line to `p = mc.p .!=0` made all problems go away!
