### ISSUE TITLE
using QuantEcon results in error

### ISSUE THREAD

**Issue by ranjanan** [QuantEcon/QuantEcon.jl#55]
On Julia 0.4.0-dev master branch which I built right now, 

"using QuantEcon" results in the following error

Warning: could not import Base.@math_const into Distributions
ERROR: LoadError: LoadError: LoadError: UndefVarError: @math_const not defined
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
while loading /Users/ranjan/.julia/v0.4/Distributions/src/constants.jl, in expression starting on line 6
while loading /Users/ranjan/.julia/v0.4/Distributions/src/Distributions.jl, in expression starting on line 252
while loading /Users/ranjan/.julia/v0.4/QuantEcon/src/QuantEcon.jl, in expression starting on line 6

I think they changed @math_const on master to something else (Irrational{:symbol} I think).

**Comment by spencerlyon2** [comment]
Indeed, that is the difference.

`Base.@math_const` was replaced with `Base.@irreational` [here](https://github.com/JuliaLang/julia/commit/5444813fb8997b22cfa7ac78438d2f4798341152).

I was going to add something to Compat.jl, but I didn't have time. 

In the mean time I just changed my local `~/.julia/v0.4/Distributions/src/constants.jl` to reflect the change

**Comment by ranjanan** [comment]
I see. This was a very recent addition. Shall I close this issue, and file it in Compat.jl? It would be relevant to a bunch of people who're using Compat

**Comment by spencerlyon2** [comment]
Yes, I think that would be good. It should be a simple addition to Compat.

The tricky part was that it is a change to an un-exported part of Base. So, I was trying to define the `@irrational` macro within `Base` by calling `eval(Base, SOME_EXPR_MAGIC)`, but I didn't quite figure out the EXPR_MAGIC before my self-alloted time allowance was up.

**Comment by spencerlyon2** [comment]
Oh, we should also link an issue in Distributions to the forthcoming issue in Compat, since that is originally where the problem messed us up

**Comment by ranjanan** [comment]
You're right, it should be notified there too.
