### ISSUE TITLE
Makorv chain: Lecture has to be revised

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.jl#57]
The line

```julia
s = mc_sample_path(P, [0.5, 0.5], 100000)
```

in the code box at the end of the [Simulation](http://quant-econ.net/jl/finite_markov.html#simulation) section has to be written as

```julia
mc = MarkovChain(P)
s = mc_sample_path(mc, [0.5, 0.5], 100000)
```

(following the change by adbd0db).

```
In [3]:

s = mc_sample_path(P, [0.5, 0.5], 100000)
LoadError: MethodError: `mc_sample_path` has no method matching mc_sample_path(::Array{Float64,2}, ::Array{Float64,1}, ::Int64)
Closest candidates are:
  mc_sample_path(!Matched::QuantEcon.MarkovChain{T<:Real}, ::Array{T,1}, ::Int64)
  mc_sample_path(!Matched::QuantEcon.MarkovChain{T<:Real}, !Matched::Int64, ::Int64)
  mc_sample_path(!Matched::QuantEcon.MarkovChain{T<:Real}, ::Array{T,1})
while loading In[3], in expression starting on line 1
```

**Comment by oyamad** [comment]
The same for `mc_compute_stationary`:

```julia
using QuantEcon
P = [.4 .6; .2 .8]
mc = MarkovChain(P)
println(mc_compute_stationary(mc))
```

instead of

```julia
using QuantEcon
P = [.4 .6; .2 .8]
println(mc_compute_stationary(P))
```

**Comment by oyamad** [comment]
[`finite_mc_solutions.ipynb`](http://nbviewer.ipython.org/github/QuantEcon/QuantEcon.jl/blob/master/solutions/finite_mc_solutions.ipynb) does not work obviously because of the problems above, but also it fails in obtaining `X_bar` and plotting in Exercise 1 because the length of the returned array of `mc_sample_path(mc, init, sample_size )` is `sample_size+1`!

**Comment by spencerlyon2** [comment]
The change for the simulation part has been incorporated into the master branch of the lectures: https://github.com/jstac/quant-econ-private/commit/e2c21bb9528c255d742a2b6b41e7fff66ed3c2be

Still need to fix the solutions and the `mc_compute_stationary` example

Thanks @oyamad

**Comment by jstac** [comment]
@oyamad @spencerlyon2 Thanks guys, I've fixed this and I'm just about to upload a new version of the lectures.  The solution notebook still needs to be fixed but I'll do that now.  Closing.
