### ISSUE TITLE
LoadErrors in 0.4

### ISSUE THREAD

**Issue by nilshg** [QuantEcon/QuantEcon.jl#65]
I ran into [this issue](https://groups.google.com/forum/#!topic/julia-users/OGOHItbHC6c) today while trying to run some code in 0.4. I don't really have an idea what's going on, and unfortunately no time to look into it now, but I still thought I'd mention it here.

**Comment by nilshg** [comment]
Apologies, should have checked the issues more thoroughly before opening this one - it seems to be a duplicate of #64.

**Comment by spencerlyon2** [comment]
No problem. Hopefully the solution from #64 helps you get things running on your machine!
