### ISSUE TITLE
BUG: rename src/distributions.jl

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#66]
I think that #64 is hitting  JuliaLang/julia#12586 and can be avoided if we simply don't use the name `src/distributions.jl` for holding the `BetaBinomial` type.

**Comment by ZacCranko** [comment]
While we're on the topic, is it possible to get that stuff located in the Distributions.jl package?

**Comment by spencerlyon2** [comment]
That would be the best long run option and what I initially intended to do.

Since implementing the bare-bones stuff that currently sits in that file, I haven't found the time to flesh out all the methods listed in the [common interface spec](http://distributionsjl.readthedocs.org/en/latest/univariate.html#common-interface) for all the distributions. Once that happens we should definitely move this upstream.

**Comment by ZacCranko** [comment]
I'm on my phone right now and walking through a park, but could you open that as an issue so we don't forget about it?
