### ISSUE TITLE
ENH: move BetaBinomial to Distributions.jl

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#67]
We really don't need to define this distribution here.

It would be far better to have this in Distributions.jl

Before this can be down we need to fill in [these methods](http://distributionsjl.readthedocs.org/en/latest/univariate.html#common-interface). 

It is highly likely that we only need to define a subset of them and the rest will be filled in via dispatch on an abstract type.

We should consult the source of Distributions.jl and construct a list of which methods we actually need to implement ourselves before submitting the PR.

**Comment by rawls238** [comment]
I've started doing this here: https://github.com/JuliaStats/Distributions.jl/pull/422

**Comment by spencerlyon2** [comment]
Great, thank you!

**Comment by rawls238** [comment]
The PR has been merged, will update the use of it in this repo once the new version is pushed. You may find the discussion in the PR interesting since it points to some imprecision issues with the `pdf` function
