### ISSUE TITLE
Docstring causes LoadErrors in 0.4

### ISSUE THREAD

**Issue by nilshg** [QuantEcon/QuantEcon.jl#69]
When `using QuantEcon` in my current 0.4.0 build, I'm getting
````
LoadError: LoadErrror: LoadError: Invalid doc exprression [eigen_solve,lu_solve,gth_solve]
````
This seems to be caused by [line 145 in mc_tools.jl](https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/mc_tools.jl#L145), simply commenting out this line fixes it for me (but probably breaks part of the documentation).

I've never written any documentation in Julia, so I don't have any idea what the problem is and how to fix it unfortunately, but it looks like an easy fix.

**Comment by spencerlyon2** [comment]
Thanks. I've been meaning to resolve this. 

Just implemented.
