### ISSUE TITLE
ERROR: LoadError: LoadError: Invalid doc expression [eigen_solve,lu_solve,gth_solve]

### ISSUE THREAD

**Issue by dbrowne** [QuantEcon/QuantEcon.jl#70]
Julia Version 0.4.0-dev+7018
Commit b6a0241* (2015-08-27 00:03 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.4.0)
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> using QuantEcon
ERROR: LoadError: LoadError: Invalid doc expression [eigen_solve,lu_solve,gth_solve]
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in require at ./loading.jl:210
while loading /Users/djb/.julia/v0.4/QuantEcon/src/mc_tools.jl, in expression starting on line 143
while loading /Users/djb/.julia/v0.4/QuantEcon/src/QuantEcon.jl, in expression starting on line 115

 - ASCIIPlots                    0.0.3
 - AnsiColor                     0.0.2
 - ArgParse                      0.2.11
 - AudioIO                       0.1.1
 - Benchmark                     0.1.0
 - Blink                         0.1.4
 - CPUTime                       0.0.4
 - Calendar                      0.4.3
 - Clang                         0.0.5
 - DataFrames                    0.6.9
 - DataStructures                0.3.12
 - Dates                         0.4.4
 - Debug                         0.1.4
 - Distributions                 0.8.3
 - Escher                        0.1.0
 - FileFind                      0.0.0
 - Gadfly                        0.3.14
 - GeoIP                         0.2.1
 - GraphViz                      0.0.4
 - Graphs                        0.5.5
 - IJulia                        0.2.5
 - Jewel                         1.0.5
 - LogParser                     0.1.0
 - Logging                       0.1.1
 - MarketData                    0.2.4
 - Memoize                       0.0.0
 - ODBC                          0.3.10
 - Pandas                        0.2.0
 - ProfileView                   0.0.12
 - ProtoBuf                      0.1.1
 - PyCall                        0.8.2
 - PyPlot                        2.0.1
 - QuantEcon                     0.2.0
 - RDatasets                     0.1.2
 - TimeData                      0.6.1
 - Timestamps                    0.0.2
 - WAV                           0.5.1
 - Winston                       0.11.12
 - ZMQ                           0.2.0

**Comment by spencerlyon2** [comment]
Thanks for the heads up. Are you using the latest released version of the package?

I think this has been resolved in master, but we haven't done a release since it was fixed.

**Comment by spencerlyon2** [comment]
If you can confirm that you are on the latest release instead of having done Pkg.checkout on this package I'll make a new release

**Comment by dbrowne** [comment]
Issue resolved.  Thanks

**Comment by spencerlyon2** [comment]
No problem. I'll make a new release so others don't have this problem also
