### ISSUE TITLE
BUG: fix ifp_solutions

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#8]
The `brent` method for Optim.jl's `optimize` function seems to be more fickle than `brentq` from scipy. 

The solution for exercise 4 didn't work because `optimize` kept complaining that the lower bound of the search region was not less than the upper bound (an annoying, albeit reasonable complaint).

**Comment by pkofod** [comment]
So what is the problem here? Is it that `opt_lb == R*a + z + b` at some points, or?

**Comment by spencerlyon2** [comment]
Yes, I guess the problem was that for some parameterization we had

```
(opt_lb,R * a + z + b) = (0.49999,0.4983333333333333)
```

I have fixed this in another branch that should be merged today.

I'll comment here when the change is merged into master.
