### ISSUE TITLE
Delete Old Branches

### ISSUE THREAD

**Issue by cc7768** [QuantEcon/QuantEcon.jl#81]
We have a lot of old branches. Not sure which ones can be deleted, but would love to clean it out. Any branches that we should leave alone (besides any that are in a PR)?

**Comment by mmcky** [comment]
Good idea - probably worth doing across all repos.

**Comment by mmcky** [comment]
@cc7768 Can this be closed?
Spencer has cleaned up the branches.

**Comment by cc7768** [comment]
I'm happy for this to be closed whenever the group feels it is clean. It looks good to me.
