### ISSUE TITLE
New `meshgrid` method?

### ISSUE THREAD

**Issue by cc7768** [QuantEcon/QuantEcon.jl#87]
Thoughts started by: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/quantecon/AQzUAsLFxFA

Often when I (and probably others) am calling `meshgrid`, the arguments that I would like to pass in are `LinSpace` types. I typically just use `collect` and pass them in. Would it make sense for us to write an additional method that takes arguments that are linspaces and simply converts them to arrays before calling out to the final function?

**Comment by spencerlyon2** [comment]
Yes, I think we should have a method that accepts two arbitrary `AbstractVector`s and collects them before handing off to the other method.

**Comment by spencerlyon2** [comment]
Actually,  it might be that the current method works if we just change the argument types to `AbstractVector` .

Either way, I'm in favor of a change here

**Comment by cc7768** [comment]
That did work. Submitting PR now.
