### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.jl#90]
Docs are pretty old. 

They still talk about the models

**Comment by caimichael** [comment]
Just spoke with Matt, since I'm in his class! I'd like to help.

**Comment by spencerlyon2** [comment]
That's great. Please let me know how you can and want to help

**Comment by spencerlyon2** [comment]
Updated to match current state of the library, but could use an overhaul. 

Right now they don't offer much in terms of exposition and are mostly just an aggregation of docstrings
